### ISSUE TITLE
初稿的基本界面策划

### ISSUE THREAD

**Issue by ivanzhang2** [haxibiao/xingqilianren#6]
![buyueta_find](https://user-images.githubusercontent.com/13308603/37943692-2551cd04-31ab-11e8-9716-c07f472a8003.gif)
- 手画,或者任何其它的sketch out 出来的东西, 反正就是让UI开发明白要做的界面需求....

**Comment by jiale888** [comment]
匹配页面
[Uploading... 发现页面.jpg ]

**Comment by jiale888** [comment]
推荐卡片页面
![推荐卡片页面.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/9e426d5a-ca63-4ea0-8599-bfb764c9feca)

**Comment by jiale888** [comment]
![消息页面.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/491f8455-705e-479c-9a8c-c41f998dabbb)
消息页面
![推荐卡片页面.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/35f6dbdc-40b5-4406-ab5d-bc75cadcbad0)
推荐卡片页面
![个人页面.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/25d9414f-e8eb-4342-8638-839441893f6d)
个人页面
![个人动态页面.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/8f23c289-78fa-49d5-821c-9d10e57bc62c)
![发现页面星期.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/5f4acce9-5f9e-4a03-8008-9bf93a5dc895)
发现页面
![发现页面.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/f681afbd-5798-4ec1-9620-1d7011253227)
![发布页面.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/07e17e0b-30d9-4328-abd1-39afb7265e39)

**Comment by jiale888** [comment]
![星期恋人手稿.jpg](https://images.zenhubusercontent.com/5aab1f764b5806bc2bcb1322/3bbb4694-8637-4b13-9612-92960719c506)
